$(document).ready(function(){
    $("#p1").hide();
    $("#p4").hide();
    $("#p5").hide();
    $("#p6").hide();
    $("#p7").hide();
    $("#p8").hide();
    $("#p9").hide();
    $("#p10").hide();
    $("#p11").hide();
    $("#p12").hide();
    $("#p13").hide();
    $("#final").hide();
    $("#detail").hide(); 
    $("#to5").hide();
    $("#noskip").hide();
    $("#skip").hide();
    $("#to7").hide();
    $("#to8").hide();
    $("#to9").hide();
    $("#to10").hide();
    $("#to11").hide();
    $("#to12").hide();
    $("#to13").hide();
    $("#tofinal").hide();

  $("#beershow").click(function(){
        $("#p1").show();
    });

  $("#to4").click(function(){
        $("#p4").show();
    });
    
   $("#moins").click(function(){
        $("#to5").show();
    });
    
   $("#plus").click(function(){
        $("#to5").show();
    });
    
    $("#to5").click(function(){
        $("#p5").show();
    });

  $("#hide").click(function(){
        $("#skip").show();
        $("#noskip").hide();
    });
    $("#skip").click(function(){
        $("#p8").show();
    });
  $("#show").click(function(){
        $("#noskip").show();
        $("#skip").hide();
    });
    $("#noskip").click(function(){
        $("#p6").show();
    });
    $("#v1").click(function(){
        $("#to7").show();
    });
    $("#v2").click(function(){
        $("#to7").show();
    });
    $("#v3").click(function(){
        $("#to7").show();
    });
    $("#v4").click(function(){
        $("#to7").show();
    });
    $("#to7").click(function(){
        $("#p7").show();
    });
    $("#myRange2").click(function(){
        $("#to8").show();
    });
    $("#to8").click(function(){
        $("#p8").show();
    });
  $("#01").click(function(){
        $("#wineimg").hide();
        $("#whiskyimg").hide();
        $("#cocktailimg").hide();
        $("#beerimg").show();
        $("#to9").show();
    });
  $("#02").click(function(){
        $("#whiskyimg").hide();
        $("#cocktailimg").hide();
        $("#beerimg").hide();
        $("#wineimg").show();
        $("#to9").show();
    });
  $("#03").click(function(){
        $("#wineimg").hide();
        $("#beerimg").hide();
        $("#cocktailimg").hide();
        $("#whiskyimg").show();
        $("#to9").show();
    });
  $("#04").click(function(){
        $("#wineimg").hide();
        $("#beerimg").hide();
        $("#whiskyimg").hide();
        $("#cocktailimg").show();
        $("#to9").show();
    });
  $("#to9").click(function(){
        $("#p9").show();
    });
  $(".beerp9").click(function(){
        $("#to10").show();
    });
  $("#to10").click(function(){
        $("#p10").show();
    });
  $("#myRange1").click(function(){
        $("#to11").show();
    });
  $("#to11").click(function(){
        $("#p11").show();
    });
  $("#p11yes").click(function(){
        $("#to12").show();
    });
  $("#p11no").click(function(){
        $("#to12").show();
    });
  $("#to12").click(function(){
        $("#p12").show();
    });
  $("#p12yes").click(function(){
        $("#to13").show();
    });
  $("#p12no").click(function(){
        $("#to13").show();
    });
  $("#to13").click(function(){
        $("#p13").show();
    });
  $("#p13yes").click(function(){
        $("#tofinal").show();
    });
  $("#p13no").click(function(){
        $("#tofinal").show();
    });
  $("#tofinal").click(function(){
        $("#final").show();
    });
});
